apiVersion: v1
name: gateways
version: 1.4.10-asm.18
appVersion: 1.4.10-asm.18
tillerVersion: ">=2.7.2"
description: Helm chart for deploying Istio gateways
keywords:
  - istio
  - ingressgateway
  - egressgateway
  - gateways
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
